{% set name = "sbi" %}
{% set version = "0.23.3" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sbi-{{ version }}.tar.gz
  sha256: 93b65b219f6e97cd03a6c979a144ee4238ed5a41205b0c8ec558d0928a549a62

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65
    - pip
  run:
    - python >={{ python_min }}
    - arviz
    - joblib >=1.0.0
    - jupyter
    - matplotlib-base
    - numpy <2.0.0
    - pillow
    - pyknos >=0.16.0
    - pyro-ppl >=1.3.1
    - scikit-learn
    - scipy <1.13
    - tensorboard
    - pytorch >=1.13.0
    - tqdm
    - pymc >=5.0.0
    - zuko >=1.2.0

test:
  imports:
    - sbi
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/sbi-dev/sbi
  summary: Simulation-based inference.
  license: Apache-2.0
  license_file: LICENSE.txt
  dev_url: https://github.com/sbi-dev/sbi
  doc_url: https://sbi-dev.github.io/sbi/

extra:
  recipe-maintainers:
    - janfb
    - matthewfeickert
