schema_version: 1

context:
  name: sbi
  version: 0.24.0
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sbi-${{ version }}.tar.gz
  sha256: 86a436bf6ccdfeb04085085e8db07aed2e86dd32c3dc88c5f2c0385fd7c46396

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=65
    - pip
  run:
    - python >=${{ python_min }}
    - arviz
    - joblib >=1.0.0
    - notebook <=6.4.12
    - matplotlib-base
    - numpy
    - pillow
    - pyknos >=0.16.0
    - pyro-ppl >=1.3.1
    - scikit-learn
    - scipy
    - tensorboard
    - pytorch >=1.13.0,<2.6.0
    - tqdm
    - pymc >=5.0.0
    - zuko >=1.2.0

tests:
  - python:
      imports:
        - sbi
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: Simulation-based inference.
  license: Apache-2.0
  license_file: LICENSE.txt
  homepage: https://github.com/sbi-dev/sbi
  repository: https://github.com/sbi-dev/sbi
  documentation: https://sbi-dev.github.io/sbi/

extra:
  recipe-maintainers:
    - janfb
    - matthewfeickert
