schema_version: 1

context:
  version: "0.26.1"
  python_min: "3.10"

package:
  name: sbi
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sbi/sbi-${{ version }}.tar.gz
  sha256: bcdcd9f19318815e8e6314523f23b727b509f02c8e657cf3696c30231d23fc07

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=65
    - pip
  run:
    - python >=${{ python_min }}
    - joblib >=1.0.0
    - matplotlib-base
    - numpy
    - pillow
    - nflows >=0.14.0
    - scikit-learn
    - scipy
    - skorch
    - tensorboard
    - pytorch >=1.13.0
    - tqdm
    - zuko >=1.2.0

tests:
  - python:
      imports:
        - sbi
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Simulation-based inference.
  license: Apache-2.0
  license_file: LICENSE.txt
  homepage: https://github.com/sbi-dev/sbi
  repository: https://github.com/sbi-dev/sbi
  documentation: https://sbi-dev.github.io/sbi/

extra:
  recipe-maintainers:
    - janfb
    - matthewfeickert
